### ISSUE TITLE
too many repeated warnings 

### ISSUE THREAD

**Issue by SikaiGGMU** [vmakeev/huawei_mesh_router#48]
my router type is huawei Q6 (lan cable) mesh router, and there are too many warings, as follows:

2023-05-09 09:09:38.286 WARNING (MainThread) [custom_components.huawei_mesh_router.update_coordinator (Huawei Router)] Can not update repeater state Api call error, status:404; code: -2, category: unauthorized
2023-05-09 09:09:38.471 WARNING (MainThread) [custom_components.huawei_mesh_router.update_coordinator (Huawei Router)] Can not update router info: Failed to get initial CSRF; reason: auth_general
2023-05-09 09:09:38.511 WARNING (MainThread) [custom_components.huawei_mesh_router.update_coordinator (Huawei Router)] Can not update router info: Api call error, status:200; code: -2, category: unauthorized
2023-05-09 09:09:38.518 WARNING (MainThread) [custom_components.huawei_mesh_router.update_coordinator (Huawei Router)] Can not update router info: Failed to get initial CSRF; reason: auth_general
2023-05-09 09:09:38.523 WARNING (MainThread) [custom_components.huawei_mesh_router.update_coordinator (Huawei Router)] Can not update router info: Failed to get initial CSRF; reason: auth_general
2023-05-09 09:09:38.528 WARNING (MainThread) [custom_components.huawei_mesh_router.update_coordinator (Huawei Router)] Can not update router info: Failed to get initial CSRF; reason: auth_general
2023-05-09 09:09:38.670 WARNING (MainThread) [custom_components.huawei_mesh_router.update_coordinator (Huawei Router)] Can not update NFC switch state: Failed to get initial CSRF; reason: auth_general
2023-05-09 09:09:38.676 WARNING (MainThread) [custom_components.huawei_mesh_router.update_coordinator (Huawei Router)] Can not update NFC switch state: Failed to get initial CSRF; reason: auth_general
2023-05-09 09:09:38.683 WARNING (MainThread) [custom_components.huawei_mesh_router.update_coordinator (Huawei Router)] Can not update NFC switch state: Failed to get initial CSRF; reason: auth_general
2023-05-09 09:09:38.688 WARNING (MainThread) [custom_components.huawei_mesh_router.update_coordinator (Huawei Router)] Can not update NFC switch state: Failed to get initial CSRF; reason: auth_general
2023-05-09 09:09:58.289 WARNING (MainThread) [custom_components.huawei_mesh_router.update_coordinator (Huawei Router)] Can not update repeater state Api call error, status:404; code: -2, category: unauthorized

Is there a way I can attenuate it?

**Comment by vmakeev** [comment]
Hi! It looks similar to the situation with the Q2S router (#34). When trying to access the router's API via a URL that is not supported by the router, the router itself breaks the connection and gives a "temporary ban" on accessing it.

I'm afraid that right now I don't have the opportunity to modify the component, because I can't reproduce this behavior on the router models that I have. 

However, if I suddenly get the necessary device at my disposal, or come up with another solution to the problem, I will report it here

**Comment by zcmk123** [comment]
my router is huawei Q6 (lan cable) too.
I found this error; maybe it's related to the mesh router's NFC switch.

The Chinese version of the Q6 router’s mesh satellite cannot be accessed directly via IP to log in to its management interface. I noticed that the plugin attempts to log in to the satellite’s management page, which shouldn’t work. Could you improve the code’s robustness? Currently, the configuration interface cannot be opened at all.

**Comment by zcmk123** [comment]
It seems the config page can’t be opened for another reason. The same error appears in other Home Assistant plugins on Core 2025.12.x

2025-12-15 17:48:53.454 ERROR (MainThread) [aiohttp.server] Error handling request from 192.168.3.157
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 510, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_app.py", line 569, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 87, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 86, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 41, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 83, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 272, in post
    return await super().post(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 76, in post
    return await self._post_impl(request, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 83, in _post_impl
    result = await self._flow_mgr.async_init(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 316, in async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 3682, in async_create_flow
    return handler.async_get_options_flow(entry)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/config/custom_components/huawei_mesh_router/config_flow.py", line 81, in async_get_options_flow
    return HuaweiControllerOptionsFlowHandler(config_entry)
  File "/config/custom_components/huawei_mesh_router/config_flow.py", line 168, in __init__
    self.config_entry = config_entry
    ^^^^^^^^^^^^^^^^^
AttributeError: property 'config_entry' of 'HuaweiControllerOptionsFlowHandler' object has no setter
